### ISSUE TITLE
Needs a little automated post-cleaning

### ISSUE THREAD

**Issue by astrochili** [mikatuo/Defold-Emmylua-Annotations#1]
Few points to improve to get a more clean version of headers:

- Remove empty modules like `camera`, `iap`, `shared_library` etc.
- Remove standard lua modules like `string`, `package` etc.
- Replace space characters to underscores in file names.

**Comment by mikatuo** [comment]
Thank you for the suggestions! Updated the archive: [defold-emmylua-1.4.1.zip](https://github.com/mikatuo/Defold-Emmylua-Annotations/releases/download/1.4.1/defold-emmylua-1.4.1.zip)
